'use client';

import { useState } from "react";
import Image from "next/image";

export default function HobbyPage() {
  interface Hobby {
    title: string;
    description: string;
    image: string[];
  }

  const hobbies: Hobby[] = [
    {
      title: "Car",
      description: "I have recently gotten into working on cars. I have a 300k mile V6 Honda Accord that I drive daily, and am currently trying to restore my dad's 1979 Datsun 280ZX coupe. At first I started with the basics on my Accord like engine and transmission oil changes, changing out the radio, and even cleaning out the intake manifold. The 280ZX has not been driven in a while and is known for being prone to rust so I am currently cleaning up the rust on the car before driving it.",
      image: ["/cars/car1.jpg","/cars/car2.jpg","/cars/car3.jpeg","/cars/car4.jpeg"],
    },
    {
      title: "Music",
      description: "I have had a long history with music, both playing and listening. I started playing the violin in elementary school, learned how to play only one really hard song on the piano during covid, and now I mainly play the electric guitar. I hope to actually learn the trumpet one day, something romantic about playing a solo off the balcony with it or something. I like to think my taste of music is diverse, from classical music to alternative/indie rock to JPop but nowadays I only listen to Japanese music. My goal is to get better at the guitar but discipline is hard to come by sometimes, regarding practice. My guitar gear is a Gibson The Paul with Seymour Duncan Seth Lovers pickups and a Yamaha THR10II amp. I also have a Yamaha guitar and bass I sometimes fiddle with.",
      image:["/guitar.jpg"]
    }
  ]

  return (
    <div className="justify-center grow shrink-0 basis-0 p-5">
      <div className="h-full">
        <div className="w-25">
          <h2 className="text-left text-2xl font-semibold">Hobbies</h2>
          <div className="w-full h-0.5 bg-gray-700 mt-1"></div>
        </div>
        <div className="w-full h-full"></div>
      </div>
      {hobbies.map((e, i) => {
        return (
          <div className="pb-3" key={i}>
            <h1 className="font-bold text-2xl">{e.title}</h1>
            <div className="pl-3">
              <div>{e.description}</div>
              <ImageGrid imageLinks={e.image}/>
            </div>
          </div>)
      })}
    </div>
  )
}


// Generated by gpt4
function ImageGrid({imageLinks} : {imageLinks:string[]}) {
  const [selected, setSelected] = useState<string | null>(null);

  return (
    <>
      {/* Grid of Images */}
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 p-4">
        {imageLinks.map((src, i) => (
          <div
            key={i}
            className="relative aspect-square cursor-pointer group"
            onClick={() => setSelected(src)}
          >
            <Image
              src={src}
              alt={`Image ${i}`}
              fill
              className="object-cover rounded-md group-hover:scale-105 transition-transform duration-300"
              sizes="(max-width: 768px) 50vw, 25vw"
            />
          </div>
        ))}
      </div>

      {/* Modal */}
      {selected && (
        <div
          className="fixed inset-0 bg-black bg-opacity-80 flex items-center justify-center z-50"
          onClick={() => setSelected(null)}
        >
          <div className="relative w-11/12 max-w-4xl aspect-video">
            <Image
              src={selected}
              alt="Enlarged"
              fill
              className="object-contain rounded-lg"
              sizes="100vw"
            />
            <button
              onClick={() => setSelected(null)}
              className="absolute top-4 right-4 text-white text-2xl"
            >
              ✕
            </button>
          </div>
        </div>
      )}
    </>
  );
}