import { useState } from "react";
import Image from "next/image";

export default function ResumePage() {

  interface Hobby {
    title: string;
    description: string;
    image: string[];
  }

  const hobbies: Hobby[] = [
    
  ]

  return (
    <div className="justify-center grow shrink-0 basis-0 p-5">
      <div className="h-full">
        <div className="w-25">
          <h2 className="text-left text-2xl font-semibold">Resume</h2>
          <div className="w-full h-0.5 bg-gray-700 mt-1"></div>
        </div>
        <div className="w-full h-full"></div>
      </div>
      <div className="mt-5">
        <><a href="/Long_Nguyenle_Resume.pdf" className="text-blue-400 underline">Here is my resume</a></>
      </div>
    </div>
  )
}

// Generated by gpt4
export function ImageGrid(imageLinks:string[]) {
  const [selected, setSelected] = useState<string | null>(null);

  return (
    <>
      {/* Grid of Images */}
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 p-4">
        {imageLinks.map((src, i) => (
          <div
            key={i}
            className="relative aspect-square cursor-pointer group"
            onClick={() => setSelected(src)}
          >
            <Image
              src={src}
              alt={`Image ${i}`}
              fill
              className="object-cover rounded-md group-hover:scale-105 transition-transform duration-300"
              sizes="(max-width: 768px) 50vw, 25vw"
            />
          </div>
        ))}
      </div>

      {/* Modal */}
      {selected && (
        <div
          className="fixed inset-0 bg-black bg-opacity-80 flex items-center justify-center z-50"
          onClick={() => setSelected(null)}
        >
          <div className="relative w-11/12 max-w-4xl aspect-video">
            <Image
              src={selected}
              alt="Enlarged"
              fill
              className="object-contain rounded-lg"
              sizes="100vw"
            />
            <button
              onClick={() => setSelected(null)}
              className="absolute top-4 right-4 text-white text-2xl"
            >
              ✕
            </button>
          </div>
        </div>
      )}
    </>
  );
}